### ISSUE TITLE
Expected number, got string

### ISSUE THREAD

**Issue by jayheavner** [timleland/vue-skycon#1]
I'm getting the following errors.

[Vue warn]: Invalid prop: type check failed for prop "width". Expected Number, got String.

[Vue warn]: Invalid prop: type check failed for prop "height". Expected Number, got String.

I'm using it exactly like the example:
`<skycon condition="clear-day" width="40" height="40"></skycon>`

What's weird is if I inspect the DOM I see the element...
`<canvas id="canvas15355928241728008" width="40" height="40"></canvas>`

but no Skycon appears. Any thoughts?

**Comment by timleland** [comment]
Good catch...just pushed a change (**v1.0.3**) that should resolve this issue. The prop expected a number but the example was passing a string. I changed it to allow numbers and string.


This example should also work. Only change here was to add colons in front so Vue knows its a number.
`<skycon condition="clear-day" :width="40" :height="40"></skycon>`
