### ISSUE TITLE
Color not working

### ISSUE THREAD

**Issue by nicholaszuccarelli** [timleland/vue-skycon#2]
Hi. Nice little package you've got here.

Unfortunately I can't change the color of the icons.
It is stuck as white.

Any idea how to fix this?

**Comment by nicholaszuccarelli** [comment]
Sorry, reopening it.
I actually am having a problem changing the color of the icons individually.

I am able to change the icon color globally via:
`Vue.use(Skycons, { color: 'white' })`

but if I want to change the color on an individual element, it doesn't work.
`<skycon condition="clear-day" :width='30' :height='30' color="white" />
`

**Comment by timleland** [comment]
I think you are using the wrong package. It should be:

`npm i vue-skycon
`
```
import VueSkycons from 'vue-skycon';
Vue.use(VueSkycons);
```

`<skycon condition="clear-day" color="red"  width="40" height="40"></skycon>`

**Comment by nicholaszuccarelli** [comment]
Now I really feel like an idiot haha ( I wasn't the one who installed the wrong package! )

Thanks man, that was the issue.

**Comment by timleland** [comment]
No problem!
