### ISSUE TITLE
Bind to condition prop doesn't update when value changes

### ISSUE THREAD

**Issue by hunterwebapps** [timleland/vue-skycon#3]
The icon doesn't update when the prop value changes. Inspection confirms that the value being passed to the condition prop does change, but the icon doesn't update.

`<skycon v-if="!!currently" :condition="currently.icon" :width="12" :height="12" />`

**Comment by timleland** [comment]
Seems to be working for me. Mind sending me some example code?

**Comment by denskiz** [comment]
I'm having the same issue. Here is my code:
<template>
  <skycon :condition="weather" width="400" height="400"></skycon>
</template>

export default {
components: {
    Skycon,
  },
  data() {
    return {
      weather: '',
    },
     mounted(){
this.weather = 'clear-day'
  },

**Comment by timleland** [comment]
@denskiz @hunterwebapps try this demo app and let me know if you still are having issues:
https://github.com/timleland/vue-skycon/tree/master/demo
